#include "adc.h"

void adc1_init(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_ADC1EN;
	
	GPIOA->CRL &= ~GPIO_CRL_CNF1;
	GPIOA->CRL &= ~GPIO_CRL_MODE1;
	
	ADC1->CR1 = 0;
	ADC1->SQR1 = 0;
	
	ADC1->CR2 |= ADC_CR2_CAL;
	while(!(ADC1->CR2 & ADC_CR2_CAL)){}
	
	ADC1->CR2 = ADC_CR2_EXTSEL;
	ADC1->CR2 |= ADC_CR2_EXTTRIG;
	ADC1->CR2 |= ADC_CR2_CONT;
	
	ADC1->SQR3 = 1;
	ADC1->CR2 |= ADC_CR2_ADON;
	ADC1->CR2 |= ADC_CR2_SWSTART;
}

void touchpad_init(void)
{
	RCC->APB2ENR |= RCC_APB2ENR_IOPAEN;
	RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;
	
	GPIOA->CRH &= ~GPIO_CRH_CNF15;
	GPIOA->CRH |= GPIO_CRH_CNF15_0;
	GPIOA->CRH |= GPIO_CRH_MODE15;
	
	GPIOB->CRL &= ~GPIO_CRL_CNF4;
	GPIOB->CRL |= GPIO_CRL_CNF4_0;
	GPIOB->CRL |= GPIO_CRL_MODE4;
	
	GPIOB->CRH &= ~GPIO_CRH_CNF10;
	GPIOB->CRH |= GPIO_CRH_CNF10_0;
	GPIOB->CRH |= GPIO_CRH_MODE10;
	
	GPIOB->CRH &= ~GPIO_CRH_CNF11;
	GPIOB->CRH |= GPIO_CRH_CNF11_0;
	GPIOB->CRH |= GPIO_CRH_MODE11;
}

void adc_read(ADC_TypeDef *ADC, uint16_t *ADC_data)
{
	*ADC_data = ADC->DR;
}
